sudo: false

language:
  - php
  - node_js

before_script:
  - curl -s https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar > /tmp/wp-cli.phar

script:
  - echo "Deploy only"

before_deploy:
  - export RELEASE_FOLDER=scribbles
  - php /tmp/wp-cli.phar package install runcommand/dist-archive
  - cp -rv ${TRAVIS_BUILD_DIR} /tmp/${RELEASE_FOLDER}
  - mv /tmp/${RELEASE_FOLDER} ${TRAVIS_BUILD_DIR}
  - php /tmp/wp-cli.phar dist-archive ${RELEASE_FOLDER} ${TRAVIS_BUILD_DIR}/${RELEASE_FOLDER}.zip --format=zip --debug

deploy:
  provider: releases
  api_key:
    secure: llTtvO9X090vIIDl13VQTDWY66reIRrvFSWxFqM6QJ4acCXYvekgyE/3PDfyAW/wTkovmLTE874ijY3EWHxyjm499PUrBJV25aT+/zEpGl2t+RYvEvXyghUreCDI6gdItwh89LQ5W54+/OYmCRgG9sogIA/q21HUd/fuFD1PlhURQzjPVBahpe7k6NgS95HdDy+AwDx1RL5MakAz5oldxwyyyAfNbXhdisiA9SRMEPXDBs0uy/6cqrIHz0AMQ4ilRczzCDanjlfjjdHGdR6Tg8WJyPT7F8ma183SkaYiUuSuPURlP7T3fHevPqwG1GX2t00JItWX+FF2aCmCblLNEFkGus4O0eUBF7t4+4gDNWLAUxgqTWHeGMmSjubw2KA9G5TDYlOFCi7xcPJyyfzeaQEvN+prWTro+q4rHL39b59givrWM9wE2tKEqUqcgmN/Wqza0sDFH8nivyH7vL5ZQtMwUd7D3QJm7+HRjTRn1tmhvyaMrQZ1d/QLmJrsiJcYTMUqN1MBiuiaEKCmwZ6rsDfmT29Ar4sBpHsO+8c0WyisHS6Vb+kwLzxZVgOj3eabbHcqfry8awZzwK/xBssV45tXd2gZWAWt6f23cyw42q6LTDARE10Dp6dZzzIA2siXWb226Ami/wH7m4b6IWD3LMBvOLkqbVoQWrWYPdRbUuc=
  file: scribbles.zip
  on:
    tags: true
    repo: godaddy/wp-scribbles-theme
  skip_cleanup: true
  overwrite: true
